// AUTO-GENERATED by gen_uart_demo.py - DO NOT EDIT
// Literal init for InstructionMemory/DataMemory under `ifdef SYNTHESIS
        mem[0] = 32'h00000009;
        mem[1] = 32'h00000003;
        mem[2] = 32'h00000007;
        mem[3] = 32'h00000001;
        mem[4] = 32'h00000005;
        mem[5] = 32'h00000005;
